//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema_plus
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public filmler()
        {
            this.rezervasyons = new HashSet<rezervasyon>();
        }
    
        public int film_id { get; set; }
        public string film_adi { get; set; }
        public string süresi { get; set; }
        public Nullable<System.DateTime> vizyon_tarihi { get; set; }
        public string tur_adi { get; set; }
        public string ozet { get; set; }
        public Nullable<decimal> imdb_puani { get; set; }
        public string yapimi { get; set; }
        public string yonetmen { get; set; }
        public string dil { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rezervasyon> rezervasyons { get; set; }
    }
}
