//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinema_plus
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaTicketEntities1 : DbContext
    {
        public CinemaTicketEntities1()
            : base("name=CinemaTicketEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<filmlers> filmlers { get; set; }
        public virtual DbSet<musterilers> musterilers { get; set; }
        public virtual DbSet<rezervasyons> rezervasyons { get; set; }
        public virtual DbSet<seanslars> seanslars { get; set; }
    }
}
